name: gyminator

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: gyminator
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gyminator
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
