// <auto-generated />
using System;
using GymTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymTracker.Infrastructure.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    [Migration("20261010145016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymTracker.Domain.Entities.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gyms");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_gyms_user_id_name")
                        .HasFilter("\"is_archived\" = false");

                    b.ToTable("gyms", (string)null);
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("DefaultGymId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_gym_id");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.HasIndex("DefaultGymId")
                        .HasDatabaseName("ix_user_settings_default_gym_id");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.Gym", null)
                        .WithMany()
                        .HasForeignKey("DefaultGymId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_settings_gyms_default_gym_id");
                });
#pragma warning restore 612, 618
        }
    }
}
